# Generated by Django 2.2 on 2019-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('header', models.CharField(blank=True, max_length=255)),
                ('paragraph', models.TextField(blank=True)),
            ],
        ),
    ]
