# Generated by Django 2.2 on 2019-04-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='logos/default_logo.png', upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=255)),
                ('nav_link', models.URLField()),
            ],
        ),
    ]
