# Generated by Django 2.2 on 2019-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0003_auto_20190428_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlinks',
            name='nav_link',
            field=models.CharField(max_length=255),
        ),
    ]
