# Generated by Django 2.2 on 2019-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0010_auto_20190428_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_paragraph',
            field=models.TextField(blank=True),
        ),
    ]
