# Generated by Django 2.2 on 2019-06-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, max_length=255)),
                ('facebook_address', models.CharField(blank=True, max_length=255)),
                ('snapchat_address', models.CharField(blank=True, max_length=255)),
                ('instgram_address', models.CharField(blank=True, max_length=255)),
                ('twitter_address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('telephone_number1', models.CharField(blank=True, max_length=255)),
                ('telephone_number2', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='logos/default_logo.png', upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=255)),
                ('nav_link', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'navbar links',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_header', models.CharField(blank=True, max_length=255)),
                ('section_paragraph', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='section_images')),
                ('weight', models.IntegerField(default=0)),
                ('page', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='alsdi.Page')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='alsdi.Section')),
            ],
            options={
                'verbose_name_plural': 'Sliders',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='carousel_images')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('paragraph', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=0)),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='alsdi.Slider')),
            ],
            options={
                'verbose_name_plural': 'Slides',
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='SectionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('paragraph', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='section_images')),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('weight', models.IntegerField(default=0)),
                ('section', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='alsdi.Section')),
            ],
            options={
                'ordering': ('weight',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.ImageField(default='album_images/default_image.png', upload_to='album_images')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='alsdi.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='alsdi.Section'),
        ),
    ]
