# Generated by Django 2.2 on 2019-06-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0002_auto_20190601_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='album_images/default_image.png', upload_to='album_images')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='alsdi.Album')),
            ],
            options={
                'verbose_name_plural': 'The images of the albums',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
