# Generated by Django 2.2 on 2019-04-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0002_logo_navbarlinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarlinks',
            options={'verbose_name_plural': 'navbar links'},
        ),
    ]
