# Generated by Django 2.2 on 2019-06-02 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0003_contact_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarlinks',
            name='page',
        ),
        migrations.AddField(
            model_name='navbarlinks',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_links', to='alsdi.Section'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='page',
            field=models.ManyToManyField(blank=True, related_name='contact_us', to='alsdi.Page'),
        ),
    ]
