# Generated by Django 2.2 on 2019-06-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0003_auto_20190601_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_address', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('project_images', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alsdi.Album')),
            ],
        ),
    ]
