# Generated by Django 2.2 on 2019-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0004_auto_20190428_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbarlinks',
            options={'ordering': ('-weight',), 'verbose_name_plural': 'navbar links'},
        ),
        migrations.AddField(
            model_name='navbarlinks',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
