# Generated by Django 2.2 on 2019-06-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0004_auto_20190602_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarlinks',
            name='section',
        ),
        migrations.AddField(
            model_name='navbarlinks',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navbar_links', to='alsdi.Page'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='page',
            field=models.ManyToManyField(blank=True, null=True, related_name='contact_us', to='alsdi.Page'),
        ),
    ]
