# Generated by Django 2.2 on 2019-04-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0005_auto_20190428_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='carousel_images')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('paragraph', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Slides',
                'ordering': ('weight',),
            },
        ),
        migrations.AlterModelOptions(
            name='navbarlinks',
            options={'ordering': ('weight',), 'verbose_name_plural': 'navbar links'},
        ),
    ]
