# Generated by Django 2.2 on 2019-06-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0005_auto_20190602_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='page',
            field=models.ManyToManyField(blank=True, related_name='contact_us', to='alsdi.Page'),
        ),
    ]
