# Generated by Django 2.2 on 2019-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0008_auto_20190428_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='telephone_number',
            new_name='telephone_number1',
        ),
        migrations.AddField(
            model_name='contact',
            name='telephone_number2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
