# Generated by Django 2.2 on 2019-06-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0009_auto_20190623_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
