# Generated by Django 2.2 on 2019-06-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0010_article_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-date_created',), 'verbose_name': 'اخر الاخبار', 'verbose_name_plural': 'اخر الاخبار'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='section',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='alsdi.Page'),
            preserve_default=False,
        ),
    ]
