# Generated by Django 2.2 on 2019-05-08 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0011_auto_20190430_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=255)),
                ('paragraph', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='section_images')),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('weight', models.IntegerField(default=0)),
                ('section', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='alsdi.Section')),
            ],
            options={
                'ordering': ('weight',),
            },
        ),
    ]
