# Generated by Django 2.2 on 2019-06-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0014_auto_20190623_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='section',
        ),
        migrations.AddField(
            model_name='article',
            name='section_block',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='alsdi.SectionBlock'),
            preserve_default=False,
        ),
    ]
