# Generated by Django 2.2 on 2019-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0016_auto_20190623_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='page',
        ),
        migrations.AddField(
            model_name='article',
            name='page',
            field=models.ManyToManyField(related_name='articles', to='alsdi.Page'),
        ),
    ]
