# Generated by Django 2.2 on 2019-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0018_auto_20190623_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_new_article',
            field=models.BooleanField(default=True),
        ),
    ]
