# Generated by Django 2.1.2 on 2019-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0022_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_sent',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ الارسال'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مستوى التشطيب'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_quotation',
            field=models.CharField(max_length=50, verbose_name='نطاق التسعير'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_subject',
            field=models.CharField(max_length=50, verbose_name='عنوان المشروع'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project_type',
            field=models.CharField(max_length=50, verbose_name='نوع المشروع'),
        ),
    ]
