# Generated by Django 2.1.2 on 2019-07-13 15:06

import alsdi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0023_auto_20190713_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='file1',
            field=models.FileField(default='default.png', upload_to='booking_files', validators=[alsdi.validators.validate_file_size], verbose_name='المخططات المعمارية'),
        ),
        migrations.AddField(
            model_name='booking',
            name='file2',
            field=models.FileField(default='default.png', upload_to='booking_files', validators=[alsdi.validators.validate_file_size], verbose_name='المخططات الانشائية'),
        ),
        migrations.AddField(
            model_name='booking',
            name='file3',
            field=models.FileField(default='default.png', upload_to='booking_files', validators=[alsdi.validators.validate_file_size], verbose_name='جداول الكميات'),
        ),
        migrations.AddField(
            model_name='booking',
            name='file4',
            field=models.FileField(default='default.png', upload_to='booking_files', validators=[alsdi.validators.validate_file_size], verbose_name='المواصفات الفنية'),
        ),
        migrations.AddField(
            model_name='booking',
            name='file5',
            field=models.FileField(default='default.png', upload_to='booking_files', validators=[alsdi.validators.validate_file_size], verbose_name='رخصة البناء'),
        ),
    ]
