# Generated by Django 2.1.2 on 2019-07-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alsdi', '0024_auto_20190713_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
